[project]
name = "server"
version = "0.1.0"
description = "AirBnB Clone Site"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.6",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
